/* Real photographs, attributed in photo-credits.html. No AI images. */
window.MALA_PATA_PHOTOS = {
  "mp-1": {
    "filename": "duck-rice.jpg",
    "title": "File:Aldea - Arroz de pato.jpg",
    "description": "Arroz de pato, duck confit, chorizo, olive, and duck cracklings at Aldea restaurant.",
    "artist": "Krista",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Aldea_-_Arroz_de_pato.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Aldea_-_Arroz_de_pato.jpg/960px-Aldea_-_Arroz_de_pato.jpg",
    "src": "./images/real/duck-rice.jpg",
    "reference": true
  },
  "mp-2": {
    "filename": "beef-rice.jpg",
    "title": "File:Paella-de-carne-con-verduras.jpg",
    "description": "Paella elaborada con arroz, tiras de carne de cerdo y ternera, acompañada de verduras tradicionales.",
    "artist": "Carlosweb95",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Paella-de-carne-con-verduras.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/9c/Paella-de-carne-con-verduras.jpg",
    "src": "./images/real/beef-rice.jpg",
    "reference": true
  },
  "mp-3": {
    "filename": "pork-prawn-rice.jpg",
    "title": "File:ValencianPaella.jpg",
    "description": "",
    "artist": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:ValencianPaella.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/ValencianPaella.jpg",
    "src": "./images/real/pork-prawn-rice.jpg",
    "reference": true
  },
  "mp-6": {
    "filename": "pork-prawn-rice.jpg",
    "title": "File:ValencianPaella.jpg",
    "description": "",
    "artist": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:ValencianPaella.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/ValencianPaella.jpg",
    "src": "./images/real/pork-prawn-rice.jpg",
    "reference": true
  },
  "mp-13": {
    "filename": "pork-prawn-rice.jpg",
    "title": "File:ValencianPaella.jpg",
    "description": "",
    "artist": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:ValencianPaella.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/ValencianPaella.jpg",
    "src": "./images/real/pork-prawn-rice.jpg",
    "reference": true
  },
  "mp-17": {
    "filename": "pork-prawn-rice.jpg",
    "title": "File:ValencianPaella.jpg",
    "description": "",
    "artist": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:ValencianPaella.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/ValencianPaella.jpg",
    "src": "./images/real/pork-prawn-rice.jpg",
    "reference": true
  },
  "mp-4": {
    "filename": "snail-rice.jpg",
    "title": "File:Plato de paella de arroz con tirabeques y caracoles.jpg",
    "description": "Plat de paella d'arròs amb tirabecs i cargols (Castelló)",
    "artist": "Juan Emilio Prades Bel",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Plato_de_paella_de_arroz_con_tirabeques_y_caracoles.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/62/Plato_de_paella_de_arroz_con_tirabeques_y_caracoles.jpg/960px-Plato_de_paella_de_arroz_con_tirabeques_y_caracoles.jpg",
    "src": "./images/real/snail-rice.jpg",
    "reference": true
  },
  "mp-5": {
    "filename": "black-rice.png",
    "title": "File:Arrosnegre.png",
    "description": "",
    "artist": "",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Arrosnegre.png",
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/89/Arrosnegre.png",
    "src": "./images/real/black-rice.png",
    "reference": true
  },
  "mp-7": {
    "filename": "banda-rice.jpg",
    "title": "File:Arroz a banda.jpg",
    "description": "Arroz a banda",
    "artist": "Javier Lastras",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_a_banda.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b6/Arroz_a_banda.jpg/960px-Arroz_a_banda.jpg",
    "src": "./images/real/banda-rice.jpg",
    "reference": true
  },
  "mp-8": {
    "filename": "chicken-rice.jpg",
    "title": "File:Arroz-con-Pollo.jpg",
    "description": "Arroz con Pollo (spanisch für „Reis mit Huhn“)",
    "artist": "Kobako",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz-con-Pollo.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/Arroz-con-Pollo.jpg/960px-Arroz-con-Pollo.jpg",
    "src": "./images/real/chicken-rice.jpg",
    "reference": true
  },
  "mp-9": {
    "filename": "senyoret-rice.jpg",
    "title": "File:Arroz del señorito.jpg",
    "description": "Arroz del señorito.",
    "artist": "Juan Emilio Prades Bel",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_del_se%C3%B1orito.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Arroz_del_se%C3%B1orito.jpg/960px-Arroz_del_se%C3%B1orito.jpg",
    "src": "./images/real/senyoret-rice.jpg",
    "reference": true
  },
  "mp-10": {
    "filename": "prawn-rice.jpg",
    "title": "File:Arroz con Carabineros y un puñado de Níscalos.jpg",
    "description": "para celebrar el santo de los Félix",
    "artist": "Manuel from Valdemoro, Spain",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg/960px-Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg",
    "src": "./images/real/prawn-rice.jpg",
    "reference": true
  },
  "mp-16": {
    "filename": "prawn-rice.jpg",
    "title": "File:Arroz con Carabineros y un puñado de Níscalos.jpg",
    "description": "para celebrar el santo de los Félix",
    "artist": "Manuel from Valdemoro, Spain",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg/960px-Arroz_con_Carabineros_y_un_pu%C3%B1ado_de_N%C3%ADscalos.jpg",
    "src": "./images/real/prawn-rice.jpg",
    "reference": true
  },
  "mp-11": {
    "filename": "lobster-rice.jpg",
    "title": "File:Arroz con bogavante en paellera.jpg",
    "description": "Paellera de Arroz con llubricante",
    "artist": "Amasuela - Luis Lafuente Agudín",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_con_bogavante_en_paellera.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Arroz_con_bogavante_en_paellera.jpg/960px-Arroz_con_bogavante_en_paellera.jpg",
    "src": "./images/real/lobster-rice.jpg",
    "reference": true
  },
  "mp-12": {
    "filename": "lobster-rice.jpg",
    "title": "File:Arroz con bogavante en paellera.jpg",
    "description": "Paellera de Arroz con llubricante",
    "artist": "Amasuela - Luis Lafuente Agudín",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_con_bogavante_en_paellera.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Arroz_con_bogavante_en_paellera.jpg/960px-Arroz_con_bogavante_en_paellera.jpg",
    "src": "./images/real/lobster-rice.jpg",
    "reference": true
  },
  "mp-14": {
    "filename": "seafood-paella.jpg",
    "title": "File:ValencianPaella.jpg",
    "description": "",
    "artist": "",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
    "source": "https://commons.wikimedia.org/wiki/File:ValencianPaella.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/0/04/ValencianPaella.jpg",
    "src": "./images/real/seafood-paella.jpg",
    "reference": true
  },
  "mp-15": {
    "filename": "vegetable-paella.jpg",
    "title": "File:Paella de verduras o arroz viudo.jpg",
    "description": "Paella de verduras o arroz viudo",
    "artist": "Avicentegil",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Paella_de_verduras_o_arroz_viudo.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Paella_de_verduras_o_arroz_viudo.jpg/960px-Paella_de_verduras_o_arroz_viudo.jpg",
    "src": "./images/real/vegetable-paella.jpg",
    "reference": true
  },
  "mp-18": {
    "filename": "octopus-rice.jpg",
    "title": "File:Arroz de polvo in Lisbon.jpg",
    "description": "Arroz de polvo (Rice with octopus) in a restaurant in Lisbon",
    "artist": "Kritzolina",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Arroz_de_polvo_in_Lisbon.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Arroz_de_polvo_in_Lisbon.jpg/960px-Arroz_de_polvo_in_Lisbon.jpg",
    "src": "./images/real/octopus-rice.jpg",
    "reference": true
  },
  "mp-19": {
    "filename": "mushroom-rice.jpg",
    "title": "File:Mushroom risotto (3990739885).jpg",
    "description": "Mushroom risotto",
    "artist": "Karen and Brad Emerson",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Mushroom_risotto_(3990739885).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Mushroom_risotto_%283990739885%29.jpg/960px-Mushroom_risotto_%283990739885%29.jpg",
    "src": "./images/real/mushroom-rice.jpg",
    "reference": true
  },
  "mp-20": {
    "filename": "fideua.jpg",
    "title": "File:Fideua - xurde.jpg",
    "description": "Una paella de fideuá, con alioli como complemento.",
    "artist": "Jorge Díaz from Madrid, Spain",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Fideua_-_xurde.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Fideua_-_xurde.jpg/960px-Fideua_-_xurde.jpg",
    "src": "./images/real/fideua.jpg",
    "reference": true
  },
  "mp-21": {
    "filename": "fideua.jpg",
    "title": "File:Fideua - xurde.jpg",
    "description": "Una paella de fideuá, con alioli como complemento.",
    "artist": "Jorge Díaz from Madrid, Spain",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Fideua_-_xurde.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Fideua_-_xurde.jpg/960px-Fideua_-_xurde.jpg",
    "src": "./images/real/fideua.jpg",
    "reference": true
  },
  "mp-22": {
    "filename": "fideua.jpg",
    "title": "File:Fideua - xurde.jpg",
    "description": "Una paella de fideuá, con alioli como complemento.",
    "artist": "Jorge Díaz from Madrid, Spain",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Fideua_-_xurde.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Fideua_-_xurde.jpg/960px-Fideua_-_xurde.jpg",
    "src": "./images/real/fideua.jpg",
    "reference": true
  },
  "mp-23": {
    "filename": "croquettes.jpg",
    "title": "File:Croquetas Caseras (7068664101).jpg",
    "description": "De jamon si no me acuerdo mal.  Las hacen de una forma distinta en el sur - con perejil creo.\nTomada durante una comida fantastica en una venta en los montes de Malaga.\nI take photos for fun and for my business blog (Say No! to the Office), food company website (The Tapas Lunch Company) and Spanish food portal (Spanish Food World).\nCopyright © 2011 Jonathan Pincas.  All Rights Reserved.\n\nPlease contact me if you're interested in using one of my pictures.",
    "artist": "Jonathan Pincas from Leon, Spain",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Croquetas_Caseras_(7068664101).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Croquetas_Caseras_%287068664101%29.jpg/960px-Croquetas_Caseras_%287068664101%29.jpg",
    "src": "./images/real/croquettes.jpg",
    "reference": true
  },
  "mp-24": {
    "filename": "samosas.jpg",
    "title": "File:Indian Samosa by clumsy home chef.jpg",
    "description": "Samosa",
    "artist": "ClumsyHomeChef",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Indian_Samosa_by_clumsy_home_chef.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/ff/Indian_Samosa_by_clumsy_home_chef.jpg/960px-Indian_Samosa_by_clumsy_home_chef.jpg",
    "src": "./images/real/samosas.jpg",
    "reference": true
  },
  "mp-25": {
    "filename": "gyozas.jpg",
    "title": "File:Deep fried gyoza.jpg",
    "description": "A plate of deep fried gyoza with some soy sauce.",
    "artist": "Douglas Perkins",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Deep_fried_gyoza.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Deep_fried_gyoza.jpg/960px-Deep_fried_gyoza.jpg",
    "src": "./images/real/gyozas.jpg",
    "reference": true
  },
  "mp-26": {
    "filename": "torrezno.jpg",
    "title": "File:Torreznos, Madrid, 2015 01.JPG",
    "description": "Torreznos",
    "artist": "Benjamín Núñez González",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Torreznos,_Madrid,_2015_01.JPG",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Torreznos%2C_Madrid%2C_2015_01.JPG/960px-Torreznos%2C_Madrid%2C_2015_01.JPG",
    "src": "./images/real/torrezno.jpg",
    "reference": true
  },
  "mp-27": {
    "filename": "pig-ear.jpg",
    "title": "File:Oreja a la plancha-Oreja de Oro.jpg",
    "description": "Ración de oreja - La oreja de oro (Madrid) -Servida con salsa de tomate",
    "artist": "Tamorlan",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Oreja_a_la_plancha-Oreja_de_Oro.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Oreja_a_la_plancha-Oreja_de_Oro.jpg/960px-Oreja_a_la_plancha-Oreja_de_Oro.jpg",
    "src": "./images/real/pig-ear.jpg",
    "reference": true
  },
  "mp-28": {
    "filename": "wings.jpg",
    "title": "File:Grilled chicken wings, Turkish style.jpg",
    "description": "Grilled chicken wings, Turkish style, accompanied by bulgur pilav and parsley-onion garni.",
    "artist": "E4024",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Grilled_chicken_wings,_Turkish_style.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Grilled_chicken_wings%2C_Turkish_style.jpg/960px-Grilled_chicken_wings%2C_Turkish_style.jpg",
    "src": "./images/real/wings.jpg",
    "reference": true
  },
  "mp-29": {
    "filename": "lacon.jpg",
    "title": "File:Lacón con patatas y grelos.jpg",
    "description": "Lacón con Patatas y Grelos",
    "artist": "jlastras",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Lac%C3%B3n_con_patatas_y_grelos.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Lac%C3%B3n_con_patatas_y_grelos.jpg/960px-Lac%C3%B3n_con_patatas_y_grelos.jpg",
    "src": "./images/real/lacon.jpg",
    "reference": true
  },
  "mp-30": {
    "filename": "nuggets.jpg",
    "title": "File:Chicken nuggets on a plate.jpg",
    "description": "Yummy!",
    "artist": "Jiafei Slay Queen",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Chicken_nuggets_on_a_plate.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/65/Chicken_nuggets_on_a_plate.jpg/960px-Chicken_nuggets_on_a_plate.jpg",
    "src": "./images/real/nuggets.jpg",
    "reference": true
  },
  "mp-31": {
    "filename": "tequenos.jpg",
    "title": "File:Tequeños vénézuéliens à Arepado (Lyon), avril 2019 (2).jpg",
    "description": "tequeños vénézuéliens à Arepado (Lyon), avril 2019.",
    "artist": "Benoît Prieur",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Teque%C3%B1os_v%C3%A9n%C3%A9zu%C3%A9liens_%C3%A0_Arepado_(Lyon),_avril_2019_(2).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Teque%C3%B1os_v%C3%A9n%C3%A9zu%C3%A9liens_%C3%A0_Arepado_%28Lyon%29%2C_avril_2019_%282%29.jpg/960px-Teque%C3%B1os_v%C3%A9n%C3%A9zu%C3%A9liens_%C3%A0_Arepado_%28Lyon%29%2C_avril_2019_%282%29.jpg",
    "src": "./images/real/tequenos.jpg",
    "reference": true
  },
  "mp-32": {
    "filename": "spring-rolls.jpg",
    "title": "File:HK KTD 九龍灣 Kln Bay KITEC 九龍灣國際展貿中心 EMax Shopping mall shop 新潮樓酒家 Crown Sky Chinese Restaurant food 春卷 oil fried spring rolls May 2023 Px3 01.jpg",
    "description": "HK KTD 九龍灣 Kln Bay KITEC 九龍灣國際展貿中心 EMax Shopping mall shop 新潮樓酒家 Crown Sky Chinese Restaurant in May 2023",
    "artist": "Fenalannm 223",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:HK_KTD_%E4%B9%9D%E9%BE%8D%E7%81%A3_Kln_Bay_KITEC_%E4%B9%9D%E9%BE%8D%E7%81%A3%E5%9C%8B%E9%9A%9B%E5%B1%95%E8%B2%BF%E4%B8%AD%E5%BF%83_EMax_Shopping_mall_shop_%E6%96%B0%E6%BD%AE%E6%A8%93%E9%85%92%E5%AE%B6_Crown_Sky_Chinese_Restaurant_food_%E6%98%A5%E5%8D%B7_oil_fried_spring_rolls_May_2023_Px3_01.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/HK_KTD_%E4%B9%9D%E9%BE%8D%E7%81%A3_Kln_Bay_KITEC_%E4%B9%9D%E9%BE%8D%E7%81%A3%E5%9C%8B%E9%9A%9B%E5%B1%95%E8%B2%BF%E4%B8%AD%E5%BF%83_EMax_Shopping_mall_shop_%E6%96%B0%E6%BD%AE%E6%A8%93%E9%85%92%E5%AE%B6_Crown_Sky_Chinese_Restaurant_food_%E6%98%A5%E5%8D%B7_oil_fried_spring_rolls_May_2023_Px3_01.jpg/960px-thumbnail.jpg",
    "src": "./images/real/spring-rolls.jpg",
    "reference": true
  },
  "mp-33": {
    "filename": "aubergine.jpg",
    "title": "File:Berenjenas con Miel.jpg",
    "description": "Aubergine crisps with honey (Berenjenas con miel) at restaurant \"Tapa\" in Edinburgh.",
    "artist": "Timo Tijhof",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Berenjenas_con_Miel.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Berenjenas_con_Miel.jpg/960px-Berenjenas_con_Miel.jpg",
    "src": "./images/real/aubergine.jpg",
    "reference": true
  },
  "mp-34": {
    "filename": "breaded-mushrooms.jpg",
    "title": "File:Breaded mushrooms in Derry.jpg",
    "description": "Breaded mushrooms in Derry.",
    "artist": "Adriao",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Breaded_mushrooms_in_Derry.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Breaded_mushrooms_in_Derry.jpg/960px-Breaded_mushrooms_in_Derry.jpg",
    "src": "./images/real/breaded-mushrooms.jpg",
    "reference": true
  },
  "mp-35": {
    "filename": "brie.jpg",
    "title": "File:A Brie Cheese at The Verandah.jpg",
    "description": "Largest of Brie Cheese on the buffet table at The Verandah",
    "artist": "Peachyeung316",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A_Brie_Cheese_at_The_Verandah.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/A_Brie_Cheese_at_The_Verandah.jpg/960px-A_Brie_Cheese_at_The_Verandah.jpg",
    "src": "./images/real/brie.jpg",
    "reference": true
  },
  "mp-36": {
    "filename": "chicken-fries.jpg",
    "title": "File:Cooked, Shredded Chicken in Bowl.jpg",
    "description": "ACES | Janet Guynn",
    "artist": "Alabama Extension",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Cooked,_Shredded_Chicken_in_Bowl.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/Cooked%2C_Shredded_Chicken_in_Bowl.jpg/960px-Cooked%2C_Shredded_Chicken_in_Bowl.jpg",
    "src": "./images/real/chicken-fries.jpg",
    "reference": true
  },
  "mp-37": {
    "filename": "quesadilla-veg.jpg",
    "title": "File:Vegetable quesadilla.jpg",
    "description": "Vegetable quesadilla at La Casita Restaurant and Cantina in Sierra Vista, Arizona.",
    "artist": "StellarD",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Vegetable_quesadilla.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Vegetable_quesadilla.jpg/960px-Vegetable_quesadilla.jpg",
    "src": "./images/real/quesadilla-veg.jpg",
    "reference": true
  },
  "mp-38": {
    "filename": "quesadilla.jpg",
    "title": "File:Quesadilles de Blanes amb salses.jpg",
    "description": "Quesadilles de Blanes amb salses.",
    "artist": "Brunnaiz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Quesadilles_de_Blanes_amb_salses.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Quesadilles_de_Blanes_amb_salses.jpg/960px-Quesadilles_de_Blanes_amb_salses.jpg",
    "src": "./images/real/quesadilla.jpg",
    "reference": true
  },
  "mp-39": {
    "filename": "tempura.jpg",
    "title": "File:Vegetable Tempura.jpg",
    "description": "Sweet potato, eggplant, and pumpkin tempura at a restaurant in Waikiki, HI.",
    "artist": "Keith Chan",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Vegetable_Tempura.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Vegetable_Tempura.jpg/960px-Vegetable_Tempura.jpg",
    "src": "./images/real/tempura.jpg",
    "reference": true
  },
  "mp-40": {
    "filename": "huevos-rotos.jpg",
    "title": "File:Huevos rotos con jamón.jpg",
    "description": "Huevos rotos con jamón",
    "artist": "jlastras",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Huevos_rotos_con_jam%C3%B3n.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Huevos_rotos_con_jam%C3%B3n.jpg/960px-Huevos_rotos_con_jam%C3%B3n.jpg",
    "src": "./images/real/huevos-rotos.jpg",
    "reference": true
  },
  "mp-41": {
    "filename": "revuelto.jpg",
    "title": "File:Revuelto de setas y jamón.jpg",
    "description": "Revuelto de setas y jamón serrano.",
    "artist": "Juan Emilio Prades Bel",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Revuelto_de_setas_y_jam%C3%B3n.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Revuelto_de_setas_y_jam%C3%B3n.jpg/960px-Revuelto_de_setas_y_jam%C3%B3n.jpg",
    "src": "./images/real/revuelto.jpg",
    "reference": true
  },
  "mp-42": {
    "filename": "bravas.jpg",
    "title": "File:Taberna Che - Braves.jpg",
    "description": "Plat de Braves a la Taverna Basca Ché",
    "artist": "Francesc Fort",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Taberna_Che_-_Braves.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Taberna_Che_-_Braves.jpg/960px-Taberna_Che_-_Braves.jpg",
    "src": "./images/real/bravas.jpg",
    "reference": true
  },
  "mp-43": {
    "filename": "mojo.jpg",
    "title": "File:Papasarrugadas.jpg",
    "description": "Papas arrugadas con mojo",
    "artist": "Fer..",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Papasarrugadas.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Papasarrugadas.jpg/960px-Papasarrugadas.jpg",
    "src": "./images/real/mojo.jpg",
    "reference": true
  },
  "mp-44": {
    "filename": "cachopo.jpg",
    "title": "File:Cachopo, KANTXA Bera-Bera 02.jpg",
    "description": "Cachopo at KANTXA Bera-Bera restaurant in San Sebastian, Spain",
    "artist": "Kent Wang",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cachopo,_KANTXA_Bera-Bera_02.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Cachopo%2C_KANTXA_Bera-Bera_02.jpg/960px-Cachopo%2C_KANTXA_Bera-Bera_02.jpg",
    "src": "./images/real/cachopo.jpg",
    "reference": true
  },
  "mp-45": {
    "filename": "beef-cheeks.jpg",
    "title": "File:Carrilleras.jpg",
    "description": "Plato de carrilleras al vino, con arroz y camote",
    "artist": "MiguelAlanCS",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Carrilleras.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Carrilleras.jpg/960px-Carrilleras.jpg",
    "src": "./images/real/beef-cheeks.jpg",
    "reference": true
  },
  "mp-46": {
    "filename": "entrecote.jpg",
    "title": "File:Steak frites at The Bar at MacArthur Place in Sonoma - Sarah Stierch.jpg",
    "description": "Steak frites at The Bar at MacArthur Place in Sonoma, California",
    "artist": "Missvain",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Steak_frites_at_The_Bar_at_MacArthur_Place_in_Sonoma_-_Sarah_Stierch.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Steak_frites_at_The_Bar_at_MacArthur_Place_in_Sonoma_-_Sarah_Stierch.jpg/960px-Steak_frites_at_The_Bar_at_MacArthur_Place_in_Sonoma_-_Sarah_Stierch.jpg",
    "src": "./images/real/entrecote.jpg",
    "reference": true
  },
  "mp-47": {
    "filename": "lamb.jpg",
    "title": "File:Panchos Lechazo Asado (3176242833).jpg",
    "description": "Pancho's Lechazo Asado",
    "artist": "michael clarke stuff",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Panchos_Lechazo_Asado_(3176242833).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Panchos_Lechazo_Asado_%283176242833%29.jpg/960px-Panchos_Lechazo_Asado_%283176242833%29.jpg",
    "src": "./images/real/lamb.jpg",
    "reference": true
  },
  "mp-48": {
    "filename": "suckling-pig.jpg",
    "title": "File:Cochinillo asado-Madrid.jpg",
    "description": "Cochinillo asado",
    "artist": "Tamorlan",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cochinillo_asado-Madrid.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Cochinillo_asado-Madrid.jpg/960px-Cochinillo_asado-Madrid.jpg",
    "src": "./images/real/suckling-pig.jpg",
    "reference": true
  },
  "mp-49": {
    "filename": "cazon.jpg",
    "title": "File:Cazón en adobo, rebozado y frito.jpg",
    "description": "Cazón en adobo, rebozado y frito.",
    "artist": "Juan Emilio Prades Bel",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Caz%C3%B3n_en_adobo,_rebozado_y_frito.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Caz%C3%B3n_en_adobo%2C_rebozado_y_frito.jpg/960px-Caz%C3%B3n_en_adobo%2C_rebozado_y_frito.jpg",
    "src": "./images/real/cazon.jpg",
    "reference": true
  },
  "mp-50": {
    "filename": "calamari.jpg",
    "title": "File:Calamares a la Romana-2009.jpg",
    "description": "Calamares a la romana",
    "artist": "Tamorlan",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Calamares_a_la_Romana-2009.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Calamares_a_la_Romana-2009.jpg/960px-Calamares_a_la_Romana-2009.jpg",
    "src": "./images/real/calamari.jpg",
    "reference": true
  },
  "mp-51": {
    "filename": "baby-squid.jpg",
    "title": "File:Puntillitas fritas.jpg",
    "description": "Puntillitas fritas. Venta Aurelio",
    "artist": "Venta Aurelio",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Puntillitas_fritas.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/35/Puntillitas_fritas.jpg/960px-Puntillitas_fritas.jpg",
    "src": "./images/real/baby-squid.jpg",
    "reference": true
  },
  "mp-52": {
    "filename": "octopus.jpg",
    "title": "File:Plato de pulpo a la gallega.jpg",
    "description": "PULPO A LA GALLEGA. Ingredientes: 1 pulpo de 2-3 kg, 1/2 kg de patatas, pimentón dulce, aceite de oliva virgen extra, sal gruesa.",
    "artist": "Juan Emilio Prades Bel",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Plato_de_pulpo_a_la_gallega.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Plato_de_pulpo_a_la_gallega.jpg/960px-Plato_de_pulpo_a_la_gallega.jpg",
    "src": "./images/real/octopus.jpg",
    "reference": true
  },
  "mp-53": {
    "filename": "goat-salad.jpg",
    "title": "File:Goat's Cheese Salad - The Oven 2025-07-24.jpg",
    "description": "Description on menu: \"WOOD FIRED GOAT'S CHEESE, BABY SPINACH, FENNEL, GRAPES, CHERRY TOMATOES, PINE NUTS & ORGANIC HONEY DRESSING\"",
    "artist": "Andy Li",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Goat%27s_Cheese_Salad_-_The_Oven_2025-07-24.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Goat%27s_Cheese_Salad_-_The_Oven_2025-07-24.jpg/960px-Goat%27s_Cheese_Salad_-_The_Oven_2025-07-24.jpg",
    "src": "./images/real/goat-salad.jpg",
    "reference": true
  },
  "mp-54": {
    "filename": "tomato-tuna.jpg",
    "title": "File:Tomato salad with onions and tuna.jpg",
    "description": "Tomato salad with onions and tuna - seen in a small restaurant in the town of Palamós, Catalonia, Spain",
    "artist": "Kritzolina",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tomato_salad_with_onions_and_tuna.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Tomato_salad_with_onions_and_tuna.jpg/960px-Tomato_salad_with_onions_and_tuna.jpg",
    "src": "./images/real/tomato-tuna.jpg",
    "reference": true
  },
  "mp-55": {
    "filename": "guacamole.jpg",
    "title": "File:Guacomole.jpg",
    "description": "Guacamole with corn chips. The stone is said to prevent the rest of the preparation from oxydizing.",
    "artist": "Popo le Chien",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Guacomole.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Guacomole.jpg/960px-Guacomole.jpg",
    "src": "./images/real/guacamole.jpg",
    "reference": true
  },
  "mp-56": {
    "filename": "burrata.jpg",
    "title": "File:Burrata with Red Tomato from Habitu Table Tsuen Wan.jpg",
    "description": "Burrata salad with Red Tomato and Green Vegetables at habitu Table Tsuen Wan",
    "artist": "Peachyeung316",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Burrata_with_Red_Tomato_from_Habitu_Table_Tsuen_Wan.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Burrata_with_Red_Tomato_from_Habitu_Table_Tsuen_Wan.jpg/960px-Burrata_with_Red_Tomato_from_Habitu_Table_Tsuen_Wan.jpg",
    "src": "./images/real/burrata.jpg",
    "reference": true
  },
  "mp-57": {
    "filename": "ham-toast.jpg",
    "title": "File:Ham&Cheese Toast.jpg",
    "description": "Ham and cheese sandwich garnished with scrambled eggs.",
    "artist": "Luigi Zuckermann",
    "license": "CC BY-SA 2.5",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
    "source": "https://commons.wikimedia.org/wiki/File:Ham%26Cheese_Toast.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Ham%26Cheese_Toast.jpg",
    "src": "./images/real/ham-toast.jpg",
    "reference": true
  },
  "mp-58": {
    "filename": "sobrasada.jpg",
    "title": "File:Pa amb sobrassada i mel.jpg",
    "description": "Bread with 'sobrassada' and honey. A simple typical way of eating sobrassada in the Catalan Countries (Catalonia, Valencia and Balearic Islands). It can be a dessert or a snack.",
    "artist": "Slastic",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Pa_amb_sobrassada_i_mel.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Pa_amb_sobrassada_i_mel.jpg/960px-Pa_amb_sobrassada_i_mel.jpg",
    "src": "./images/real/sobrasada.jpg",
    "reference": true
  },
  "mp-59": {
    "filename": "tomato-toast.jpg",
    "title": "File:Tomato Bruschetta.jpg",
    "description": "Tomato Bruschetta",
    "artist": "Michael_Spencer",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tomato_Bruschetta.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Tomato_Bruschetta.jpg/960px-Tomato_Bruschetta.jpg",
    "src": "./images/real/tomato-toast.jpg",
    "reference": true
  },
  "mp-60": {
    "filename": "goat-toast.jpg",
    "title": "File:Salade mesclun et chèvre chaud sur toasts.jpg",
    "description": "Mesclun, petits légumes marinés et chèvre chaud aux herbes sur toasts.",
    "artist": "DocteurCosmos",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Salade_mesclun_et_ch%C3%A8vre_chaud_sur_toasts.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Salade_mesclun_et_ch%C3%A8vre_chaud_sur_toasts.jpg/960px-Salade_mesclun_et_ch%C3%A8vre_chaud_sur_toasts.jpg",
    "src": "./images/real/goat-toast.jpg",
    "reference": true
  },
  "mp-61": {
    "filename": "steak-toast.jpg",
    "title": "File:Philly cheesesteak sandwich.jpg",
    "description": "A Philly cheesesteak sandwich (link)",
    "artist": "jeffreyw",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Philly_cheesesteak_sandwich.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Philly_cheesesteak_sandwich.jpg/960px-Philly_cheesesteak_sandwich.jpg",
    "src": "./images/real/steak-toast.jpg",
    "reference": true
  },
  "mp-62": {
    "filename": "salmon-toast.jpg",
    "title": "File:Avocado & Smoked Salmon On Sourdough Toast - Amo 2026-02-04.jpg",
    "description": "Avocado & Smoked Salmon On Sourdough Toast",
    "artist": "Andy Li",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Avocado_%26_Smoked_Salmon_On_Sourdough_Toast_-_Amo_2026-02-04.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Avocado_%26_Smoked_Salmon_On_Sourdough_Toast_-_Amo_2026-02-04.jpg/960px-Avocado_%26_Smoked_Salmon_On_Sourdough_Toast_-_Amo_2026-02-04.jpg",
    "src": "./images/real/salmon-toast.jpg",
    "reference": true
  },
  "mp-63": {
    "filename": "gulas.jpg",
    "title": "File:Tosta de Gulas.jpg",
    "description": "Tosta de gulas (sucedáneo de las angulas).",
    "artist": "Tamorlan",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tosta_de_Gulas.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f1/Tosta_de_Gulas.jpg/960px-Tosta_de_Gulas.jpg",
    "src": "./images/real/gulas.jpg",
    "reference": true
  },
  "mp-64": {
    "filename": "carrot-cake.jpg",
    "title": "File:Carrot cake slice and latte - Saltmarsh Farmhouse & Cafe 2024-12-19.jpg",
    "description": "Carrot cake slice and latte",
    "artist": "Andy Li",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Carrot_cake_slice_and_latte_-_Saltmarsh_Farmhouse_%26_Cafe_2024-12-19.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Carrot_cake_slice_and_latte_-_Saltmarsh_Farmhouse_%26_Cafe_2024-12-19.jpg/960px-Carrot_cake_slice_and_latte_-_Saltmarsh_Farmhouse_%26_Cafe_2024-12-19.jpg",
    "src": "./images/real/carrot-cake.jpg",
    "reference": true
  },
  "mp-65": {
    "filename": "apple-cake.jpg",
    "title": "File:Apple cake with vanilla ice cream 2.jpg",
    "description": "Simple and easy apple pie served with vanilla ice cream, on a gingham tablecloth in Lysekil, Sweden. Image focus stacked from five photos using Photoshop.\nRecipe:\n\nIngredients: 150 g butter, 1 dl sugar, 3 dl all-purpose flour, 1 dl rolled oats, 3 large apples\nDirections: Mix sugar, flour and oats in a bowl. Cut the butter into smaller cubes and add to the mix. Work the butter into the dry ingredients using pinching and kneading motions, until the butter is evenly mixed in. The result should not be a smooth dough, but rather small lumps. Pour the lumps into a pan; a regular medium springform pan will do nicely. Work the lumpy dough so that it covers the bottom of the pan and a couple of cm up against the sides. Peel and slice the apples, and put them in the pan. Sprinkle with some sugar and cinnamon. Bake in the middle of oven at 225 °C for about 25-30 minutes. Allow to cool a bit before serving with vanilla ice cream.",
    "artist": "W.carter",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Apple_cake_with_vanilla_ice_cream_2.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Apple_cake_with_vanilla_ice_cream_2.jpg/960px-Apple_cake_with_vanilla_ice_cream_2.jpg",
    "src": "./images/real/apple-cake.jpg",
    "reference": true
  },
  "mp-66": {
    "filename": "fig-cake.jpg",
    "title": "File:Beautiful decorated cake with figs and blueberry from above. (49574602871).jpg",
    "description": "Beautiful decorated cake with figs and blueberry from above.",
    "artist": "Nenad Stojkovic from Srbija",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Beautiful_decorated_cake_with_figs_and_blueberry_from_above._(49574602871).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Beautiful_decorated_cake_with_figs_and_blueberry_from_above._%2849574602871%29.jpg/960px-Beautiful_decorated_cake_with_figs_and_blueberry_from_above._%2849574602871%29.jpg",
    "src": "./images/real/fig-cake.jpg",
    "reference": true
  },
  "mp-67": {
    "filename": "lava-cake.jpg",
    "title": "File:Chocolate lava cake.jpg",
    "description": "Warm chocolate lava cake",
    "artist": "sanctumsolitude",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Chocolate_lava_cake.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/95/Chocolate_lava_cake.jpg/960px-Chocolate_lava_cake.jpg",
    "src": "./images/real/lava-cake.jpg",
    "reference": true
  },
  "mp-68": {
    "filename": "sundae.jpg",
    "title": "File:Strawberry Ice Cream Sundae (TheatreCafé C's).jpg",
    "description": "ストロベリーサンデー(あきた芸術劇場ミルハス内「シアターカフェC's(シーズ) 」)",
    "artist": "掬茶",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Strawberry_Ice_Cream_Sundae_(TheatreCaf%C3%A9_C%27s).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/Strawberry_Ice_Cream_Sundae_%28TheatreCaf%C3%A9_C%27s%29.jpg/960px-Strawberry_Ice_Cream_Sundae_%28TheatreCaf%C3%A9_C%27s%29.jpg",
    "src": "./images/real/sundae.jpg",
    "reference": true
  },
  "mp-69": {
    "filename": "waffle.jpg",
    "title": "File:A&W chocolate sauce on ice cream waffle malaysia.jpg",
    "description": "Recently launched dessert in Petaling Jaya branch",
    "artist": "Vincent60030",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:A%26W_chocolate_sauce_on_ice_cream_waffle_malaysia.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/A%26W_chocolate_sauce_on_ice_cream_waffle_malaysia.jpg/960px-A%26W_chocolate_sauce_on_ice_cream_waffle_malaysia.jpg",
    "src": "./images/real/waffle.jpg",
    "reference": true
  },
  "mp-70": {
    "filename": "cheesecake.jpg",
    "title": "File:Chestnut Basque Cheesecake - MOGUMOGU 2024-11-02.jpg",
    "description": "With pear compote, chestnut purée, and a Halloween \"ghost\" made with rice paper.",
    "artist": "Andy Li",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Chestnut_Basque_Cheesecake_-_MOGUMOGU_2024-11-02.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Chestnut_Basque_Cheesecake_-_MOGUMOGU_2024-11-02.jpg/960px-Chestnut_Basque_Cheesecake_-_MOGUMOGU_2024-11-02.jpg",
    "src": "./images/real/cheesecake.jpg",
    "reference": true
  },
  "mp-71": {
    "filename": "espresso.jpg",
    "title": "File:Espresso BW 1.jpg",
    "description": "A cup of espresso",
    "artist": "Berthold Werner",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Espresso_BW_1.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Espresso_BW_1.jpg/960px-Espresso_BW_1.jpg",
    "src": "./images/real/espresso.jpg",
    "reference": true
  },
  "mp-72": {
    "filename": "espresso.jpg",
    "title": "File:Espresso BW 1.jpg",
    "description": "A cup of espresso",
    "artist": "Berthold Werner",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Espresso_BW_1.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/Espresso_BW_1.jpg/960px-Espresso_BW_1.jpg",
    "src": "./images/real/espresso.jpg",
    "reference": true
  },
  "mp-73": {
    "filename": "cortado.jpg",
    "title": "File:CaféCortado(Tallat).jpg",
    "description": "Café Cortado (Tallat en Cataluña)",
    "artist": "Charles Haynes",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Caf%C3%A9Cortado(Tallat).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Caf%C3%A9Cortado%28Tallat%29.jpg/960px-Caf%C3%A9Cortado%28Tallat%29.jpg",
    "src": "./images/real/cortado.jpg",
    "reference": true
  },
  "mp-74": {
    "filename": "latte.jpg",
    "title": "File:Cafeconleche.jpg",
    "description": "Café con leche (Coffee with milk)",
    "artist": "Jeremy Keith from Brighton & Hove, United Kingdom",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Cafeconleche.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Cafeconleche.jpg/960px-Cafeconleche.jpg",
    "src": "./images/real/latte.jpg",
    "reference": true
  },
  "mp-75": {
    "filename": "tea.jpg",
    "title": "File:Cup of tea isolated on white background - Petr Kratochvil.jpg",
    "description": "Mint tea on white background.",
    "artist": "Petr Kratochvil",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Cup_of_tea_isolated_on_white_background_-_Petr_Kratochvil.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/92/Cup_of_tea_isolated_on_white_background_-_Petr_Kratochvil.jpg/960px-Cup_of_tea_isolated_on_white_background_-_Petr_Kratochvil.jpg",
    "src": "./images/real/tea.jpg",
    "reference": true
  },
  "mp-76": {
    "filename": "cola.jpg",
    "title": "File:Glass cola.jpg",
    "description": "A glass of cold cola with three icecubes and two lemon pieces.",
    "artist": "pic_p_ter",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_cola.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Glass_cola.jpg/960px-Glass_cola.jpg",
    "src": "./images/real/cola.jpg",
    "reference": true
  },
  "mp-77": {
    "filename": "energy.jpg",
    "title": "File:Red Bull ice.jpg",
    "description": "Left a glass of Red Bull with ice, right the can it came from",
    "artist": "Klaas van Buiten",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "source": "https://commons.wikimedia.org/wiki/File:Red_Bull_ice.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Red_Bull_ice.jpg/960px-Red_Bull_ice.jpg",
    "src": "./images/real/energy.jpg",
    "reference": true
  },
  "mp-78": {
    "filename": "juice.jpg",
    "title": "File:Orange juice in a glass (4430731914).jpg",
    "description": "Orange juice in a glass",
    "artist": "Geoff Peters from Vancouver, BC, Canada",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Orange_juice_in_a_glass_(4430731914).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Orange_juice_in_a_glass_%284430731914%29.jpg/960px-Orange_juice_in_a_glass_%284430731914%29.jpg",
    "src": "./images/real/juice.jpg",
    "reference": true
  },
  "mp-79": {
    "filename": "tonic.jpg",
    "title": "File:Schweppes Indian Tonic Water (front laying down).jpg",
    "description": "Front of an old Schweppes Indian Tonic Water bottle laying down. No idea of date",
    "artist": "Reedy",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Schweppes_Indian_Tonic_Water_(front_laying_down).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Schweppes_Indian_Tonic_Water_%28front_laying_down%29.jpg/960px-Schweppes_Indian_Tonic_Water_%28front_laying_down%29.jpg",
    "src": "./images/real/tonic.jpg",
    "reference": true
  },
  "mp-80": {
    "filename": "vermouth.jpg",
    "title": "File:Vermouth.jpg",
    "description": "",
    "artist": "",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Vermouth.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/1/15/Vermouth.jpg",
    "src": "./images/real/vermouth.jpg",
    "reference": true
  },
  "mp-81": {
    "filename": "cream-liqueur.jpg",
    "title": "File:Glass of Baileys.jpg",
    "description": "Un bicchiere di Baileys con ghiaccio",
    "artist": "Christine Sponchia",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_Baileys.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Glass_of_Baileys.jpg/960px-Glass_of_Baileys.jpg",
    "src": "./images/real/cream-liqueur.jpg",
    "reference": true
  },
  "mp-82": {
    "filename": "tinto.jpg",
    "title": "File:Tinto de verano.jpg",
    "description": "Dicen que hay vida más allá de la cerveza. Dicen...",
    "artist": "Arkangel from Granada, España",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tinto_de_verano.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Tinto_de_verano.jpg/960px-Tinto_de_verano.jpg",
    "src": "./images/real/tinto.jpg",
    "reference": true
  },
  "mp-83": {
    "filename": "tinto.jpg",
    "title": "File:Tinto de verano.jpg",
    "description": "Dicen que hay vida más allá de la cerveza. Dicen...",
    "artist": "Arkangel from Granada, España",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Tinto_de_verano.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Tinto_de_verano.jpg/960px-Tinto_de_verano.jpg",
    "src": "./images/real/tinto.jpg",
    "reference": true
  },
  "mp-84": {
    "filename": "water.jpg",
    "title": "File:Glass of water ouside.jpg",
    "description": "dining outside, ice water",
    "artist": "Kurt Kaiser",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_water_ouside.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Glass_of_water_ouside.jpg/960px-Glass_of_water_ouside.jpg",
    "src": "./images/real/water.jpg",
    "reference": true
  },
  "mp-85": {
    "filename": "gin-tonic.jpg",
    "title": "File:Gin and Tonic with ingredients.jpg",
    "description": "Gin and tonic with lime in a highball glass, with the ingredients behind",
    "artist": "NotFromUtrecht",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gin_and_Tonic_with_ingredients.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Gin_and_Tonic_with_ingredients.jpg/960px-Gin_and_Tonic_with_ingredients.jpg",
    "src": "./images/real/gin-tonic.jpg",
    "reference": true
  },
  "mp-86": {
    "filename": "beer.jpeg",
    "title": "File:My Estrella (87219665).jpeg",
    "description": "500px provided description: Always when i`m visiting Spain i try to drink one of my favourite beer!\nThat is Estrella Galicia!\nAs a spanish boy raised in Germany i like how it tastes.\nBut coming back to that picture ..\n\nI liked the scenery going on even with the noisy kids in the background having fun. This beer gave me tranquility ;-) [#bokeh ,#mallorca ,#glass ,#wine ,#galicia ,#beer ,#barrel ,#estrella ,#alcudia ,#food porn ,#estrella galicia]",
    "artist": "Daniel Guillin",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_Estrella_(87219665).jpeg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/My_Estrella_%2887219665%29.jpeg/960px-My_Estrella_%2887219665%29.jpeg",
    "src": "./images/real/beer.jpeg",
    "reference": true
  },
  "mp-87": {
    "filename": "beer.jpeg",
    "title": "File:My Estrella (87219665).jpeg",
    "description": "500px provided description: Always when i`m visiting Spain i try to drink one of my favourite beer!\nThat is Estrella Galicia!\nAs a spanish boy raised in Germany i like how it tastes.\nBut coming back to that picture ..\n\nI liked the scenery going on even with the noisy kids in the background having fun. This beer gave me tranquility ;-) [#bokeh ,#mallorca ,#glass ,#wine ,#galicia ,#beer ,#barrel ,#estrella ,#alcudia ,#food porn ,#estrella galicia]",
    "artist": "Daniel Guillin",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_Estrella_(87219665).jpeg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/My_Estrella_%2887219665%29.jpeg/960px-My_Estrella_%2887219665%29.jpeg",
    "src": "./images/real/beer.jpeg",
    "reference": true
  },
  "mp-88": {
    "filename": "beer-bottle.jpg",
    "title": "File:EstrellaGaliciaEspecial.jpg",
    "description": "A bottle of Estrella Galicia Especial beer.",
    "artist": "Miguel Andrade",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:EstrellaGaliciaEspecial.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/EstrellaGaliciaEspecial.jpg/960px-EstrellaGaliciaEspecial.jpg",
    "src": "./images/real/beer-bottle.jpg",
    "reference": true
  },
  "mp-89": {
    "filename": "beer-1906.jpg",
    "title": "File:1906 Reserva Especial (Hijos de Rivera).jpg",
    "description": "Bierflasche (0.33 Liter)",
    "artist": "Pansebert",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:1906_Reserva_Especial_(Hijos_de_Rivera).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/1906_Reserva_Especial_%28Hijos_de_Rivera%29.jpg/960px-1906_Reserva_Especial_%28Hijos_de_Rivera%29.jpg",
    "src": "./images/real/beer-1906.jpg",
    "reference": true
  },
  "mp-90": {
    "filename": "beer-1906.jpg",
    "title": "File:1906 Reserva Especial (Hijos de Rivera).jpg",
    "description": "Bierflasche (0.33 Liter)",
    "artist": "Pansebert",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:1906_Reserva_Especial_(Hijos_de_Rivera).jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/1906_Reserva_Especial_%28Hijos_de_Rivera%29.jpg/960px-1906_Reserva_Especial_%28Hijos_de_Rivera%29.jpg",
    "src": "./images/real/beer-1906.jpg",
    "reference": true
  },
  "mp-91": {
    "filename": "beer-gf.jpg",
    "title": "File:Gluten free beer in a market.jpg",
    "description": "Gluten free beer made from sorghum in an American supermarket; to be used to illustrate articles about gluten-free beer, celiac disease and related topics (not as an advertisement for this specific brand)",
    "artist": "Flickr user Arlen",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Gluten_free_beer_in_a_market.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Gluten_free_beer_in_a_market.jpg/960px-Gluten_free_beer_in_a_market.jpg",
    "src": "./images/real/beer-gf.jpg",
    "reference": true
  },
  "mp-92": {
    "filename": "beer-zero.jpeg",
    "title": "File:My Estrella (87219665).jpeg",
    "description": "500px provided description: Always when i`m visiting Spain i try to drink one of my favourite beer!\nThat is Estrella Galicia!\nAs a spanish boy raised in Germany i like how it tastes.\nBut coming back to that picture ..\n\nI liked the scenery going on even with the noisy kids in the background having fun. This beer gave me tranquility ;-) [#bokeh ,#mallorca ,#glass ,#wine ,#galicia ,#beer ,#barrel ,#estrella ,#alcudia ,#food porn ,#estrella galicia]",
    "artist": "Daniel Guillin",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_Estrella_(87219665).jpeg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/My_Estrella_%2887219665%29.jpeg/960px-My_Estrella_%2887219665%29.jpeg",
    "src": "./images/real/beer-zero.jpeg",
    "reference": true
  },
  "mp-93": {
    "filename": "beer-zero.jpeg",
    "title": "File:My Estrella (87219665).jpeg",
    "description": "500px provided description: Always when i`m visiting Spain i try to drink one of my favourite beer!\nThat is Estrella Galicia!\nAs a spanish boy raised in Germany i like how it tastes.\nBut coming back to that picture ..\n\nI liked the scenery going on even with the noisy kids in the background having fun. This beer gave me tranquility ;-) [#bokeh ,#mallorca ,#glass ,#wine ,#galicia ,#beer ,#barrel ,#estrella ,#alcudia ,#food porn ,#estrella galicia]",
    "artist": "Daniel Guillin",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:My_Estrella_(87219665).jpeg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/My_Estrella_%2887219665%29.jpeg/960px-My_Estrella_%2887219665%29.jpeg",
    "src": "./images/real/beer-zero.jpeg",
    "reference": true
  },
  "mp-94": {
    "filename": "red-wine.jpg",
    "title": "File:Glass of red wine.jpg",
    "description": "A beautiful picture of a glass of red wine alongside with a candle lamp.",
    "artist": "Photos Public Domain",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_red_wine.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Glass_of_red_wine.jpg/960px-Glass_of_red_wine.jpg",
    "src": "./images/real/red-wine.jpg",
    "reference": true
  },
  "mp-95": {
    "filename": "red-wine.jpg",
    "title": "File:Glass of red wine.jpg",
    "description": "A beautiful picture of a glass of red wine alongside with a candle lamp.",
    "artist": "Photos Public Domain",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_red_wine.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Glass_of_red_wine.jpg/960px-Glass_of_red_wine.jpg",
    "src": "./images/real/red-wine.jpg",
    "reference": true
  },
  "mp-96": {
    "filename": "red-wine.jpg",
    "title": "File:Glass of red wine.jpg",
    "description": "A beautiful picture of a glass of red wine alongside with a candle lamp.",
    "artist": "Photos Public Domain",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_red_wine.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Glass_of_red_wine.jpg/960px-Glass_of_red_wine.jpg",
    "src": "./images/real/red-wine.jpg",
    "reference": true
  },
  "mp-97": {
    "filename": "white-wine.jpg",
    "title": "File:Two Chenin Blanc wines in glass.jpg",
    "description": "Two Chenin Blanc wines of different origin, style and age. Left Raats Chenin Blanc 2007, a young, oaked Chenin Blanc from Stellenbosch, South Africa. Right Clos de la Bergerie 2001, a Chenin Blanc from Loire with some bottle age, and most likely produced in a slightly oxidative style and with a proportion of grapes affected by noble rot.",
    "artist": "Tomas er",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Two_Chenin_Blanc_wines_in_glass.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Two_Chenin_Blanc_wines_in_glass.jpg/960px-Two_Chenin_Blanc_wines_in_glass.jpg",
    "src": "./images/real/white-wine.jpg",
    "reference": true
  },
  "mp-98": {
    "filename": "white-wine.jpg",
    "title": "File:Two Chenin Blanc wines in glass.jpg",
    "description": "Two Chenin Blanc wines of different origin, style and age. Left Raats Chenin Blanc 2007, a young, oaked Chenin Blanc from Stellenbosch, South Africa. Right Clos de la Bergerie 2001, a Chenin Blanc from Loire with some bottle age, and most likely produced in a slightly oxidative style and with a proportion of grapes affected by noble rot.",
    "artist": "Tomas er",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Two_Chenin_Blanc_wines_in_glass.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Two_Chenin_Blanc_wines_in_glass.jpg/960px-Two_Chenin_Blanc_wines_in_glass.jpg",
    "src": "./images/real/white-wine.jpg",
    "reference": true
  },
  "mp-99": {
    "filename": "white-wine.jpg",
    "title": "File:Two Chenin Blanc wines in glass.jpg",
    "description": "Two Chenin Blanc wines of different origin, style and age. Left Raats Chenin Blanc 2007, a young, oaked Chenin Blanc from Stellenbosch, South Africa. Right Clos de la Bergerie 2001, a Chenin Blanc from Loire with some bottle age, and most likely produced in a slightly oxidative style and with a proportion of grapes affected by noble rot.",
    "artist": "Tomas er",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "source": "https://commons.wikimedia.org/wiki/File:Two_Chenin_Blanc_wines_in_glass.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Two_Chenin_Blanc_wines_in_glass.jpg/960px-Two_Chenin_Blanc_wines_in_glass.jpg",
    "src": "./images/real/white-wine.jpg",
    "reference": true
  },
  "mp-100": {
    "filename": "red-bottle.jpg",
    "title": "File:Bottle and glass of red wine.jpg",
    "description": "wine vins",
    "artist": "congerdesign",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Bottle_and_glass_of_red_wine.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Bottle_and_glass_of_red_wine.jpg/960px-Bottle_and_glass_of_red_wine.jpg",
    "src": "./images/real/red-bottle.jpg",
    "reference": true
  },
  "mp-101": {
    "filename": "red-bottle.jpg",
    "title": "File:Bottle and glass of red wine.jpg",
    "description": "wine vins",
    "artist": "congerdesign",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "source": "https://commons.wikimedia.org/wiki/File:Bottle_and_glass_of_red_wine.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Bottle_and_glass_of_red_wine.jpg/960px-Bottle_and_glass_of_red_wine.jpg",
    "src": "./images/real/red-bottle.jpg",
    "reference": true
  },
  "mp-102": {
    "filename": "white-bottle.jpg",
    "title": "File:Glass of White Wine shot with a bottle of white wine - Evan Swigart.jpg",
    "description": "Glass of White Wine shot with a bottle of white wine.",
    "artist": "Evan Swigart from Chicago, USA",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "source": "https://commons.wikimedia.org/wiki/File:Glass_of_White_Wine_shot_with_a_bottle_of_white_wine_-_Evan_Swigart.jpg",
    "url": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Glass_of_White_Wine_shot_with_a_bottle_of_white_wine_-_Evan_Swigart.jpg",
    "src": "./images/real/white-bottle.jpg",
    "reference": true
  },
  "mp-103": {
    "filename": "cider.jpg",
    "title": "File:Bulmerscider.jpg",
    "description": "Bulmers Original Cider, Canadian Market (bilingual label). 568ml/pint bottle with glass of Bulmers Original Cider.",
    "artist": "Jason Gaudet",
    "license": "Public domain",
    "licenseUrl": "",
    "source": "https://commons.wikimedia.org/wiki/File:Bulmerscider.jpg",
    "url": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Bulmerscider.jpg/960px-Bulmerscider.jpg",
    "src": "./images/real/cider.jpg",
    "reference": true
  }
};
